#!/usr/bin/env python3
"""Generate an as1600 source dump of a .bin ROM (16-bit big-endian words).

Usage: dump_rom.py ROM.bin BASE_ADDR_HEX OUT.asm [PATCHES.py]

PATCHES.py, when given, is a Python literal dict mapping word address (int) to
an as1600 expression string that replaces the original word at that address.
The original value is kept in a comment so every patch site stays auditable.
The expressions are expected to be symbols defined by the including source
(patches.asm); building with those symbols set to the original values must
reproduce the original ROM byte-for-byte (the `make verify-org` guard).
"""
import ast
import sys


def main():
    rom_path, base_hex, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    base = int(base_hex, 16)
    patches = {}
    if len(sys.argv) > 4:
        with open(sys.argv[4]) as f:
            patches = ast.literal_eval(f.read())

    data = open(rom_path, "rb").read()
    assert len(data) % 2 == 0, "odd byte count"
    words = [(data[i] << 8) | data[i + 1] for i in range(0, len(data), 2)]

    unused = set(patches) - set(range(base, base + len(words)))
    assert not unused, f"patch addresses outside ROM: {[hex(a) for a in unused]}"

    with open(out_path, "w") as out:
        out.write(f"; Generated by tools/dump_rom.py from {rom_path} -- DO NOT EDIT\n")
        out.write(f"        ORG     ${base:04X}\n")
        row = []
        for i, w in enumerate(words):
            addr = base + i
            if addr in patches:
                if row:
                    out.write(f"        DECLE   {', '.join(row)}\t; ${addr - len(row):04X}\n")
                    row = []
                out.write(f"        DECLE   {patches[addr]}\t; ${addr:04X} PATCH (orig ${w:04X})\n")
            else:
                row.append(f"${w:04X}")
                if len(row) == 8:
                    out.write(f"        DECLE   {', '.join(row)}\t; ${addr - 7:04X}\n")
                    row = []
        if row:
            out.write(f"        DECLE   {', '.join(row)}\t; ${base + len(words) - len(row):04X}\n")


if __name__ == "__main__":
    main()
